<?php
/**
 * @file
 * Code for the FOCUS Directory of professionals feature.
 */

include_once 'focus_directory_of_professionals.features.inc';

/**
 * Implements hook_node_insert().
 */
function focus_directory_of_professionals_node_insert($node) {
	if ($node->type == 'focus_directory_of_professionals') {
		_focus_directory_of_professionals_new_user($node);
		_focus_directory_of_professionals_send_request($node);		
	}
}

/**
 * Function to send an email when creating a new professional.
 *
 * @param mixed $node
 *    Get the node id.
 *
 */
function _focus_directory_of_professionals_new_user($node) {
	// Send email to admin.
	global $base_url;    
	$to = 'javiersanchezflores@hotmail.com';
	$subject = t('FOCUS - New professional');
	$practiceName_text = array(
	  '@urlInvitation' => $base_url . "/new-professional_en",
	);
	$body = t('
		<div style="background: rgba(244, 244, 244, 0.54); border-radius: 2px; padding-top: 10px;">
			<div class="header">
				<div style="width: 120px; margin: 0 auto;">
					<img style="float:left; margin-right:5px;" alt="Logo FOCUS" src="http://94.23.87.115:50080/focus/platform/themes/focus/images/icono_logo_focus.png">
					<h1 style="font-size:23px; margin-right: 5px; font-weight: 500;">FOCUS</h1>
				</div>
				<div style="background:#0065A2; padding: 1px 20px; text-align: center;">
					<p style="color:#ffffff;">frailty management optimization through EIP AHA commitments and utilization of stakeholders input</p>
				</div>
				<img style="width:100%;" alt="Header FOCUS" src="http://94.23.87.115:50080/focus/platform/sites/default/files/slider5.jpg">
			</div>
			<div>
				<p style="padding: 20px 0 0 20px;">You have new invitation to accept a new professional. You can accept or decline the invitation in the next link:</p>
				<a style="padding: 20px;" href="@urlInvitation"><b>Reply invitation</b></a>
			</div>
			<div style="background:#0065A2; padding: 10px 20px; border-radius: 0 0 2px 2px; display: flex; margin-top: 40px;">
				<div style="float: left; width: 80%;">
					<p style="color:#FFFFFF;">&copy; FOCUS 2017</p>
				</div>
				<div style="float:left; width:20%; padding-top:7px; color:#FFFFFF;">
					<a href="https://twitter.com/focusonfrailty"><img style="padding-top:-7px;" alt="Icon twitter" src="http://94.23.87.115:50080/focus/platform/themes/focus/images/twitter.png"></a>
					<a style="margin: 5px 0 0 5px; color: #FFFFFF; position:absolute;" href="https://twitter.com/focusonfrailty">Follow us on Twitter</a>
				</div>
			</div>
		</div>
		', $practiceName_text);

	$params = array(
	  'subject' => $subject,
	  'body' => $body,
	);

	drupal_mail('focus_directory_of_professionals', 'focus_directory_of_professionals_mail', $to, language_default(), $params);
}

function _focus_directory_of_professionals_send_request($node){
	// Send email to user (Send request).
	$name_professional = $node->field_name_professional['und'][0]['value'];
	$lastname_professional = $node->field_last_name_professional['und'][0]['value'];
	$mail_professional = $node->field_email_professional['und'][0]['email'];

	global $base_url;    
	$to = $mail_professional;
	$subject = t('FOCUS - New professional request send');
	$data_professional = array(
	  '@nameProfessional' => $name_professional,
	  '@lastnameProfessional' => $lastname_professional,
	  '@mail_professional' => $mail_professional,
	);
	$body = t('
		<div style="background: rgba(244, 244, 244, 0.54); border-radius: 2px; padding-top: 10px;">
			<div class="header">
				<div style="width: 120px; margin: 0 auto;">
					<img style="float:left; margin-right:5px;" alt="Logo FOCUS" src="http://94.23.87.115:50080/focus/platform/themes/focus/images/icono_logo_focus.png">
					<h1 style="font-size:23px; margin-right: 5px; font-weight: 500;">FOCUS</h1>
				</div>
				<div style="background:#0065A2; padding: 1px 20px; text-align: center;">
					<p style="color:#ffffff;">frailty management optimization through EIP AHA commitments and utilization of stakeholders input</p>
				</div>
				<img style="width:100%;" alt="Header FOCUS" src="http://94.23.87.115:50080/focus/platform/sites/default/files/slider5.jpg">
			</div>
			<div>
				<p style="padding: 20px 0 0 20px;">Your request to add @nameProfessional @lastnameProfessional has been sended.</p>
			</div>
			<div style="background:#0065A2; padding: 10px 20px; border-radius: 0 0 2px 2px; display: flex; margin-top: 40px;">
				<div style="float: left; width: 80%;">
					<p style="color:#FFFFFF;">&copy; FOCUS 2017</p>
				</div>
				<div style="float:left; width:20%; padding-top:7px; color:#FFFFFF;">
					<a href="https://twitter.com/focusonfrailty"><img style="padding-top:-7px;" alt="Icon twitter" src="http://94.23.87.115:50080/focus/platform/themes/focus/images/twitter.png"></a>
					<a style="margin: 5px 0 0 5px; color: #FFFFFF; position:absolute;" href="https://twitter.com/focusonfrailty">Follow us on Twitter</a>
				</div>
			</div>
		</div>
		', $data_professional);

	$params = array(
	  'subject' => $subject,
	  'body' => $body,
	);

	drupal_mail('focus_directory_of_professionals', 'focus_directory_of_professionals_mail', $to, language_default(), $params);
}

/**
 * Function to send an email to the admin when creating a new professional.
 *
 * @param string $key
 *    Get the $key.
 * @param mixed $message
 *    Get the $message.
 * @param array $params
 *    Get the $params.
 */
function focus_directory_of_professionals_mail($key, &$message, $params) {
	if ($key == 'focus_directory_of_professionals_mail') {
		$message['headers']['MIME-Version'] = '1.0';
		$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
		$message['headers']['Content-Transfer-Encoding'] = '8Bit';
		$message['subject'] = $params['subject'];
		$message['body'][] = $params['body'];
	}
}